### ISSUE TITLE
Release in PyPi?

### ISSUE THREAD

**Issue by HTenkanen** [realead/cykhash#1]
Hi @realead,

and thanks for writing this library, I've been using it successfully now with my own projects and it has provided quite nice speedup for doing lookups compared to numpy/pandas 👍  

I was wondering that would you consider releasing this in PyPi and perhaps also in conda-forge so that it would be easier to integrate the package with other projects? 

Cheers,
Henrikki

**Comment by realead** [comment]
Thanks for your feedback. Until now I didn't consider that, as it was only my pet project and nobody used it.

When there will be a little bit time (right now is a somewhat scarce resource) I will give the library a small polish (a guess  at least the documentation needs to be improved, as right now it is only a protocol of my changes/experiments, as well some signatures) and publish it on PyPi.

**Comment by taoliu** [comment]
Second @HTenkanen :)

**Comment by realead** [comment]
Can be installed from PyPi via

     pip install cykhash

now. It is a somewhat simplistic solution, as it only has the source distribution and no wheels.. 

There is clearly some  room for improvement:

 * it might be a good idea to include cython to `setup_requires`. My assumption that everybody has cython already installed might not be true:)
* I don't include Cython-generated c-files into distribution (contrary to the recommendation in the Cython-documentation: https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules), because IMO having only pyx-files is more future-proof: The current Cython version might generate c-files which don't work with future CPython versions - they will have to be regenerated and having c-files in the distribution and enforcing them to be rebuild by Cython is another stumbling block. But maybe having C-files is still the better way.

Next step would be to release in conda-forge, which might take some time.

**Comment by HTenkanen** [comment]
@realead Excellent! Thanks a lot! 

>it might be a good idea to include cython to setup_requires. My assumption that everybody has cython already installed might not be true:)

Indeed, I would still add Cython to the requirements (that's an easy fix) because now starting from a clean environment produces an error that's due to the missing Cython installation:
![image](https://user-images.githubusercontent.com/6659534/83131551-e5adb200-a0d7-11ea-9116-3ac0745b2245.png)

Other than that the package was very easy to install. 

I can also help you out setting up the conda-forge distribution. 👍

**Comment by taoliu** [comment]
@realead Thank you! I will try it out!

**Comment by realead** [comment]
1.0.2 is released, which can be installed in a clean environment.

@HTenkanen I've no experience with conda-forge, so any help is appreciated!

**Comment by HTenkanen** [comment]
@realead Okay, I now created a recipe for conda-forge. Could you @realead go and mention that you are okay that cykhash will be published in conda-forge. You can do that by adding a comment here:
https://github.com/conda-forge/staged-recipes/pull/11946

In addition, do you want to be included as a recipe maintainer as well? (as you're the author, I think it makes a lot of sense). I now only included myself but I can include you there as well (requires acceptance from all maintainers).

**Comment by HTenkanen** [comment]
@realead Okay, now the package is available from conda-forge! 💪 I also updated the docs and created the PR #2 for those.

**Comment by realead** [comment]
cykhash-1.0.2 was released in PyPi and conda-forge. Thank you Henrikki @HTenkanen!
